apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "4pd-vgpu.scheduler" . }}-newversion
  labels:
    app.kubernetes.io/component: 4pd-scheduler
    {{- include "4pd-vgpu.labels" . | nindent 4 }}
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: {{ .Values.schedulerName }}
    extenders:
    - urlPrefix: "https://127.0.0.1:443"
      filterVerb: filter
      bindVerb: bind
      nodeCacheCapable: true
      weight: 1
      httpTimeout: 30s
      enableHTTPS: true
      tlsConfig:
        insecure: true
      managedResources:
      - name: {{ .Values.resourceName }}
        ignoredByScheduler: true
      - name: {{ .Values.resourceMem }}
        ignoredByScheduler: true
      - name: {{ .Values.resourceCores }}
        ignoredByScheduler: true
      - name: {{ .Values.resourceMemPercentage }}
        ignoredByScheduler: true
      - name: {{ .Values.resourcePriority }}
        ignoredByScheduler: true
      - name: {{ .Values.mluResourceName }}
        ignoredByScheduler: true
      - name: {{ .Values.mluResourceMem }}
        ignoredByScheduler: true