{{- if .Values.mockDevicePlugin.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "hami-vgpu.mock-device-plugin" . }}
  namespace: {{ include "hami-vgpu.namespace" . }}
spec:
  selector:
    matchLabels:
      name: hami-mock-dp-ds
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: hami-mock-dp-ds
    spec:
      serviceAccountName: {{ include "hami-vgpu.mock-device-plugin" . }}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: {{ include "hami.mockDevicePlugin.image" . }}
      imagePullPolicy: {{ .Values.devicePlugin.image.pullPolicy }}
        name: hami-mock-dp-cntr
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - ./k8s-device-plugin
          - -v=5
          - --device-config-file=/device-config.yaml
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            drop: ["ALL"]
            add: ["SYS_ADMIN"]
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: sys
            mountPath: /sys
          - name: device-config
            mountPath: /device-config.yaml
            subPath: device-config.yaml
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: device-config
          configMap:
            name: {{ include "hami-vgpu.scheduler" . }}-device
{{- end -}}