{{- if .Values.devicePlugin.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hami-vgpu.device-plugin" . }}
  namespace: {{ include "hami-vgpu.namespace" . }}
  labels:
    app.kubernetes.io/component: "hami-device-plugin"
    {{- include "hami-vgpu.labels" . | nindent 4 }}
{{- end -}}
