{{- if .Values.devicePlugin.enabled }}
{{- if and .Values.devicePlugin.createRuntimeClass .Values.devicePlugin.runtimeClassName }}
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ .Values.devicePlugin.runtimeClassName }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
handler: nvidia
{{- end }}
{{- end -}}
