{{- if not .Values.dra.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hami-vgpu.scheduler" . }}
  namespace: {{ include "hami-vgpu.namespace" . }}
  labels:
    app.kubernetes.io/component: "hami-scheduler"
    {{- include "hami-vgpu.labels" . | nindent 4 }}
---
{{- if .Values.mockDevicePlugin.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hami-vgpu.mock-device-plugin" . }}
  namespace: {{ include "hami-vgpu.namespace" . }}
{{- end -}}
{{- end }}
